---
title: "Trade Policy in the Shadow of Power"
subtitle: "Quantifying Military Coercion in the International System"
date: "9 April 2020"
author: Brendan Cooley
position: Ph.D. Candidate
institution: Princeton University
email: "bcooley (at) princeton.edu"
note: These slides available at brendancooley.com/tpsp

bibliography: /Users/brendancooley/Dropbox (Princeton)/References/library.bib
biblio-style: apsr

backgroundTitle: "02_figs/cover.jpg"

output:
  revealjs::revealjs_presentation:
    template: "css/cooley-reveal.html"
    css: "css/cooley-reveal.css"
    backgroundTransition: none
    transition: none
    self_contained: false
    # reveal_plugins: ["notes"]
    lib_dir: index_files
    reveal_options:
      slideNumber: false
      progress: false
      controls: false      
    includes:
      after_body: "css/plugins.html"
---

```{r, echo=FALSE, warning=FALSE, message=FALSE, results='hide'}

code_dir <- "01_code/"
figs_dir <- "02_figs/"
slides_dir <- "slides/"

size = "mid/"

tpspPath <- "~/Dropbox (Princeton)/1_Papers/tpsp/01_data/"
dataPath <- paste0(tpspPath, "data/", size)
resultsPath <- paste0(tpspPath, "results/", size)
estimatesPath <- paste0(resultsPath, "estimates/")

helperPath <- "~/Dropbox (Princeton)/14_Software/R/"
helperFiles <- list.files(helperPath)
for (i in helperFiles) {
  source(paste0(helperPath, i))
}

libs <- c("tidyverse")
ipak(libs)

year <- read_csv(paste0(dataPath, "year.csv"), col_names=FALSE) %>% pull(.)

# references from paper
if (file.exists('references.RData')) load('references.RData')

```

```{r, child="slides/introduction.rmd"}
```

```{r, child="slides/model.rmd"}
```

```{r, child="slides/data.rmd"}
```

```{r, child="slides/estimation.rmd"}
```

```{r, child="slides/results.rmd"}
```

```{r, child="slides/counterfactuals.rmd"}
```

```{r, child="slides/conclusion.rmd"}
```

# Thank You {.aligncenter}

[brendancooley.com](http://brendancooley.com)

[bcooley@princeton.edu](mailto:bcooley@princeton.edu)

# Table of Contents {id="toc"}

<div id="left">

**Sections**

1. <a href="#/introduction">Introduction</a>
2. <a href="#/model">Model</a>
3. <a href="#/data">Data</a>
4. <a href="#/estimation">Estimation</a>
5. <a href="#/results">Results</a>
6. <a href="#/counterfactuals">Conterfactuals</a>
7. <a href="#/conclusion">Conclusion</a>

</div>

<div id="right">

**Appendix**

1. <a href="#/barriers">Estimated Dyadic Policy Barriers</a>
2. <a href="#/economyA">Economy (Overview)</a>
3. <a href="#/frechet">Cost Distribution</a>
4. <a href="#/milex">Military Expenditure</a>
5. <a href="#/calibration">Economy (Calibration)</a>

</div>


```{r, child="slides/appendix.rmd"}
```

<!-- hide references -->
<hr style="height:30em; visibility:hidden;" />