---
title: | 
	| Trade Policy in the Shadow of Power
	| \tiny \hfill
    | \Large Quantifying Military Coercion in the International System
author:
	- name: Brendan Cooley
      affiliation: Ph.D. Candidate, Department of Politics, Princeton University
date: \today
abstract: In international relations, how does latent military coercion affect governments’ policy choices? Because militarily powerful governments can credibly threaten to impose their policy preferences by force, weaker governments may adjust their policy choices to avoid costly conflict. This setting raises an inference problem -- do observed policies reflect the preferences of the governments that adopted them or the military constraints of the anarchic international system? Here, I investigate the role of this “shadow of power” in determining trade policy. Specifically, I build a model of trade policy choice under threat that allows me to measure empirically governments’ underlying trade policy preferences, the returns to military advantage, and the extent to which power projection capacity degrades across space. I then estimate the parameters of the model using data on governments' observed trade policies in 2011. I find that geographic distance is not an impediment to the projection of force but that there are increasing returns to military advantage in the technology of coercion. Through counterfactual experiments, I quantify the effect of military constraints on the international economy and governments' welfare. These and other exercises shed light on how military power affects international economic exchange, and how expectations about exchange affect governments’ military strategies.
thanks: Thanks to Geneveive Bates, Allison Carnegie, Jim Fearon, Haosen Ge, Mike Gibilisco, Kyle Haynes, Helen Milner, Sayumi Miyano, Steve Monroe, In Young Park, Jim Qian, Kris Ramsay, and Joe Ruggiero for comments and discussions on many earlier versions of this project. Thanks also to audiences at the American Political Science Association's 2019 annual meeting and the 2020 conference on Formal Models of International Relations.
# jelcodes: JEL codes go here

bibliography: /Users/brendancooley/Dropbox (Princeton)/References/library.bib
biblio-style: apsr

papersize: letter
documentclass: article
geometry: margin=1.25in
link-citations: true

output:
	fig_caption: yes
    citation_package: natbib

---

```{r libs, echo=FALSE, warning=FALSE, message=FALSE, results='hide'}

helperPath <- "~/Dropbox (Princeton)/14_Software/R/"
helperFiles <- list.files(helperPath)
for (i in helperFiles) {
  source(paste0(helperPath, i))
}

libs <- c("knitr", "tidyverse", "countrycode", "kableExtra", "latex2exp", "patchwork", "ggpubr")
ipak(libs)

# not available
AwarEntry <- "NA"
DGammac <- "NA"
Pc <- "NA"
Pm <- "NA"
Aeconomy <- "NA"
AeconomyC <- "NA"
Achat <- "NA"
# Aproofs <- "NA"
Aalphagamma <- "NA"
Ampec <- "NA"
AestimationAlg <- "NA"

# load references picked up later in document
if (file.exists('references.RData')) load('references.RData')

# setup definition, assumption, proposition, lemma tickers
Dtick <- 1
Atick <- 1
Ptick <- 1
Ltick <- 1

size <- "mid/"

sections_dir <- "03_sections/"

tpspPath <- "~/Dropbox (Princeton)/1_Papers/tpsp/01_data/"
dataPath <- paste0(tpspPath, "data/", size)
resultsPath <- paste0(tpspPath, "results/", size)
estimatesPath <- paste0(resultsPath, "estimates/")

# economic parameters 
theta <- read_csv(paste0(dataPath, "theta.csv"), col_names=FALSE) %>% pull(.)
beta <- read_csv(paste0(dataPath, "beta.csv"), col_names=FALSE) %>% pull(.)
ccodes <- read_csv(paste0(dataPath, "ccodes.csv"), col_names=FALSE)
y <- read_csv(paste0(dataPath, "y.csv"), col_names=FALSE)
Y <- read_csv(paste0(dataPath, "year.csv"), col_names=FALSE) %>% pull(.)
N <- length(ccodes %>% pull(.))

# data
tauM <- read_csv(paste0(dataPath, "tau.csv"), col_names=FALSE) %>% as.matrix()
tau <- read_csv(paste0(dataPath, "tau.csv"), col_names=FALSE)
milex <- read_csv(paste0(dataPath, "milex.csv"), col_names=FALSE)
# b_vals <- read_csv(paste0(resultsPath, "b_vals.csv"), col_names=FALSE)
W <- read_csv(paste0(dataPath, "cDists.csv"), col_names=FALSE)

# estimates
v_star <- read_csv(paste0(estimatesPath, "v.csv"), col_names=FALSE)
alpha1 <- read_csv(paste0(estimatesPath, "alpha1.csv"), col_names=FALSE) %>% pull(.)
c_hat <- read_csv(paste0(estimatesPath, "c_hat.csv"), col_names=FALSE) %>% pull(.)
gamma <- read_csv(paste0(estimatesPath, "gamma.csv"), col_names=FALSE) %>% pull(.)
# cb_ratio_mean <- read_csv(paste0(estimatesPath, "cb_ratio_mean.csv"), col_names=FALSE) %>% pull(.)
rcv_eq <- read_csv(paste0(estimatesPath, "rcv_eq.csv"), col_names=FALSE)

# results
# Ghatft <- read_csv(paste0(resultsPath, "Ghatft.csv"), col_names=FALSE)
# rcv0 <- read_csv(paste0(resultsPath, "rcv0.csv"), col_names=FALSE)
# rcv1 <- read_csv(paste0(resultsPath, "rcv1.csv"), col_names=FALSE)

options(scipen=999)

```

\newpage

# Introduction

```{r, child = paste0(sections_dir, "introduction.rmd")}
```

## Literature

```{r, child = paste0(sections_dir, "literature.md")}
```

# Data and Calibration of Economy

```{r, child = paste0(sections_dir, "data.rmd")}
```

# Model

```{r, child = paste0(sections_dir, "model.md")}
```


# Estimation

```{r, child = paste0(sections_dir, "estimation.rmd")}
```

# Results

```{r, child = paste0(sections_dir, "results.rmd")}
```

# Counterfactual: Coercion-Free World

<!-- ```{r, child = paste0(sections_dir, "counterfactuals.rmd")}
``` -->


# Conclusion

```{r, child = paste0(sections_dir, "conclusion.md")}
```

\clearpage

# Appendix

```{r Appendix Numbering, echo=FALSE, warning=FALSE, message=FALSE, results='hide'}

a <- 1

# reset definition, assumption, proposition, lemma tickers
Dtick <- 1
Atick <- 1
Ptick <- 1
Ltick <- 1

Aeconomy <- LETTERS[a]
```

## `r Aeconomy`: Economy

```{r, child = paste0(sections_dir, "Aeconomy.md")}
```

```{r, echo=FALSE, warning=FALSE, message=FALSE, results='hide'}

a <- a + 1

# reset definition, assumption, proposition, lemma tickers
Dtick <- 1
Atick <- 1
Ptick <- 1
Ltick <- 1

AeconomyC <- LETTERS[a]

```

## `r AeconomyC`: Calibration of Economy

```{r, child = paste0(sections_dir, "AeconomyC.rmd")}
```
\clearpage

# References

```{r, echo=FALSE, warning=FALSE, message=FALSE, results='hide'}

save.image('references.RData')

```