# Power and Preferences {id="introduction"}

<div class="fragment">

> "A has **power** over B to the extent that he can get B to do something that B **would not otherwise do.**"
> 
> - @Dahl1957

</div>
<div class="fragment">

**Power in Anarchy**

- Anarchy: no higher authority to compel states to resolve disputes peacefully
- Anarchy $\implies$ powerful governments can impose policies on others by force
- Bargaining critique: policies adjust to reflect **shadow of power**
  + @Brito1985, @Fearon1995, @Art1996; @Powell1999

</div>
<div class="fragment">

**Detecting the Exercise of Power: An Inference Problem**

- Dahl: What would B do in the absence of A's power?
- Do observed policies reflect **preferences** of the governments that adopted them or **constraints of anarchy?**

</div>

## Trade Policy and Gunboat Diplomacy {id="gunboats"}

**What Do Governments Want?**

- **Protectionism** at home [@Grossman1994; @Gawande2009]
  + Domestic distributional conflict: @Mayer1984, @Rogowski1987; @Grossman1994
  + Fiscal capacity: @Rodrik2008, @Queralt2015
- **Openness** abroad [@Grossman2016]
	+ Market access externalities: @Ossa2011, @Ossa2012
	+ Lobbying and Trade Policy: Firms pressure governments to negotiate reductions in trade barriers abroad [@Osgood2016; @Kim2017] 
- Induces **conflicts of interest** between governments

. . . 

**Gunboat Diplomacy**

- Powerful governments impose openness on weaker counterparts
	+ @Findlay2007
- Peacetime regimes: empire, hegemony, and hierarchy  	
	+ @Gallagher1953, @Krasner1976, @Gilpin1981, @Kindleberger1986, @Lake2013
	+ Economic effects: @Berger2013

. . . 

**Does Trade Policy Matter?**

- Tariffs small, aggregate policy-induced trade frictions large
  + ~order of magnitude larger than tariffs [@Cooley2019b] (<a href="#/barriers">barriers</a>)
- Welfare effects of trade frictions
  + @Autor2013, @Costinot2015, @Goldberg2016

## Anarchy and Inference: Approach {id="approach"}

**A Coercive International Political Economy**

$$
\left\{ \bm{\theta}, \bm{M} \right\} \rightarrow \bm{\tau}
$$

- Observables
	+ $\bm{M}$ -- governments' military endowment (expenditure)
	+ $\bm{\tau}$ -- governments' trade policies
- Unobservables
	+ $\bm{\theta}$ -- structural parameters (preferences and power projection capacity)


. . . 

**Estimation:** $\left\{ \bm{\tau}, \bm{M} \right\} \rightarrow \bm{\theta}$

. . . 

**Counterfactuals:** $\left\{ \bm{\theta}^\prime, \bm{M}^\prime \right\} \rightarrow \bm{\tau}^\prime$

- Shadow of power
  + Effect of changing military endowments on trade policy
- Liberal/commercial peace
  + Effect of changing preferences for openness on probability of war