# Model (Overview) {id="model"}

<div class="fragment">

- Governments indexed $i \in \left\{ 1, ..., N \right\}$

</div>
<div class="fragment">

**Sequence**

1. ($\tilde{\bm{\tau}}$) Governments make trade policy announcements
2. Wars
    + Winners impose free trade on vanquished governments
3. ($h(\bm{\tau})$) Economic (general equilibrium, @Eaton2002) consequences of announced/imposed trade policies

</div>
<div class="fragment">

**Payoffs**

$$
V_i \left( h(\bm{\tau}); \color{bcOrange} v_i \color{black} \right)
$$

- $\color{bcOrange} v_i$ - latent preference for protectionist policies

</div>

## ($h(\bm{\tau})$) Economy {id="economy"}

$$
\bm{\tau} = \begin{pmatrix}
\tau_{11} & \cdots & \cdots & \cdots & \tau_{1N} \\
\vdots & \ddots & \vdots & \iddots & \vdots \\
\vdots & \cdots & \tau_{ij} & \cdots & \vdots \\
\vdots & \iddots & \vdots & \ddots & \vdots \\
\tau_{N1} & \cdots & \cdots & \cdots & \tau_{NN}
\end{pmatrix}
$$

## ($h(\bm{\tau})$) Economy

$$
\bm{\tau} = \begin{pmatrix}
\tau_{11} & \cdots & \cdots & \cdots & \tau_{1N} \\
\vdots & \ddots & \vdots & \iddots & \vdots \\
\vdots & \cdots & \color{bcOrange} \tau_{ij} & \cdots & \vdots \\
\vdots & \iddots & \vdots & \ddots & \vdots \\
\tau_{N1} & \cdots & \cdots & \cdots & \tau_{NN}
\end{pmatrix}
$$

<hr style="height:2em; visibility:hidden;" />

- $\color{bcOrange} \tau_{ij}$: trade barrier government $i$ imposes on imports from $j$

## ($h(\bm{\tau})$) Economy

$$
\bm{\tau} = \begin{pmatrix}
\color{bcOrange} \tau_{11} & \color{bcOrange} \cdots & \color{bcOrange} \cdots & \color{bcOrange} \cdots & \color{bcOrange} \tau_{1N} \\
\vdots & \ddots & \vdots & \iddots & \vdots \\
\vdots & \cdots & \tau_{ij} & \cdots & \vdots \\
\vdots & \iddots & \vdots & \ddots & \vdots \\
\tau_{N1} & \cdots & \cdots & \cdots & \tau_{NN}
\end{pmatrix}
$$

<hr style="height:2em; visibility:hidden;" />

$$
\color{bcOrange} \bm{\tau}_1 = \begin{pmatrix} \tau_{11} & \cdots & \cdots & \cdots & \tau_{1N}
\end{pmatrix}
$$

<hr style="height:2em; visibility:hidden;" />

- Government 1's trade policy

## ($h(\bm{\tau})$) Economy {id="economyEnd"}

$$
\color{bcOrange} \bm{\tau} \color{black} = \begin{pmatrix}
\tau_{11} & \cdots & \cdots & \cdots & \tau_{1N} \\
\vdots & \ddots & \vdots & \iddots & \vdots \\
\vdots & \cdots & \tau_{ij} & \cdots & \vdots \\
\vdots & \iddots & \vdots & \ddots & \vdots \\
\tau_{N1} & \cdots & \cdots & \cdots & \tau_{NN}
\end{pmatrix}
$$

<hr style="height:2em; visibility:hidden;" />

$$
\color{bcOrange} h(\bm{\tau}) \rightarrow \begin{pmatrix}
w_1 \\
\vdots \\
w_N
\end{pmatrix} = \bm{w}
$$

<a href="#/economyA">Economy Details</a>

## Government Objective

$$
h(\bm{\tau}) \rightarrow \begin{pmatrix}
w_1 \\
\vdots \\
w_N
\end{pmatrix} = \color{bcOrange} \bm{w}
$$

<hr style="height:1em; visibility:hidden;" />

- $X_{ij}(\color{bcOrange} \bm{w} \color{black})$: $i$'s imports of goods from $j$

. . . 

**Revenues from Policy Distortions**

$$
r_i(\color{bcOrange} \bm{w} \color{black}; v_i) = \sum_j (\tau_{ij} - v_i) X_{ij}(\color{bcOrange} \bm{w} \color{black})
$$

## Government Objective

$$
h(\bm{\tau}) \rightarrow \begin{pmatrix}
w_1 \\
\vdots \\
w_N
\end{pmatrix} = \bm{w}
$$

<hr style="height:1em; visibility:hidden;" />

- $X_{ij}(\bm{w})$: $i$'s imports of goods from $j$

**Revenues from Policy Distortions**

$$
r_i(\bm{w}; \color{bcOrange} v_i \color{black}) = \sum_{j \neq i} (\tau_{ij} - \color{bcOrange} v_i \color{black}) X_{ij}(\bm{w})
$$

- $\color{bcOrange} v_i \color{black} \in [1, \infty)$ controls $i$'s preferences over the level of protection

. . . 

**Adjusted Consumer Income**

$$
\tilde{Y}_i(\bm{w})  = w_i L_i + r_i(\bm{w}; \color{bcOrange} v_i \color{black})
$$

**Indirect Utility**

$$
V_i \left( h(\bm{\tau}); \color{bcOrange} v_i \color{black} \right)
$$

## Wars I {id="wars"}

- Directed dyad-specific war costs held as **private information** to prospective attacker
	+ $c_{ji}$ -- cost $j$ incurs to invade $i$
- Wars fought to impose free trade on target

$$
\bm{\tau}_i^\prime = \left( 1, \dots, 1 \right) = \bm{1}_i
$$

. . .

**Conquest Values**

- $V_j(\bm{1}_i; \tilde{\bm{\tau}}_{-i})$ -- $j$'s value for imposing free trade on $i$

. . .

**Peace Condition**

$$
V_j \left( \bm{1}_i, \tilde{\bm{\tau}}_{-i}; v_j \right) - c_{ji} \leq V_j \left( \tilde{\bm{\tau}}, v_j \right)
$$

## Wars II

**Cost Distribution**

$$
\hat{c}_{ji} = \frac{c_{ji}}{V_j \left( \bm{\tau}; v_j \right)}
$$

$$
\text{Pr}\left( \frac{1}{\hat{c}_{ji}} \leq \frac{1}{\hat{c}} \right) = \hat{F}_{ji} \left( \frac{1}{\hat{c}} \right) = \exp \left( -\frac{1}{\hat{C}_j} \left( \frac{M_j}{M_i} \right)^{\gamma} (W_{ji})^{-\alpha} \hat{c}^{\eta} \right) .
$$

## Wars II

**Cost Distribution**

$$
\hat{c}_{ji} = \frac{c_{ji}}{V_j \left( \bm{\tau}; v_j \right)}
$$

$$
\text{Pr}\left( \frac{1}{\hat{c}_{ji}} \leq \frac{1}{\hat{c}} \right) = \hat{F}_{ji} \left( \frac{1}{\hat{c}} \right) = \exp \left( -\frac{1}{\color{bcOrange}  \hat{C}_j \color{black}} \left( \frac{M_j}{M_i} \right)^{\gamma} (W_{ji})^{-\alpha} \hat{c}^{\eta} \right) .
$$

- $\color{bcOrange} \hat{C}_j$ -- attacker-specific cost-shifter

## Wars II

**Cost Distribution**

$$
\hat{c}_{ji} = \frac{c_{ji}}{V_j \left( \bm{\tau}; v_j \right)}
$$

$$
\text{Pr}\left( \frac{1}{\hat{c}_{ji}} \leq \frac{1}{\hat{c}} \right) = \hat{F}_{ji} \left( \frac{1}{\hat{c}} \right) = \exp \left( -\frac{1}{\hat{C}_j} \left( \frac{ \color{bcOrange} M_j \color{black} }{ \color{bcOrange} M_i \color{black} } \right)^{\gamma} (Z_{ji})^{-\alpha} \hat{c}^{\eta} \right) .
$$

- $\hat{C}_j$ -- attacker-specific cost-shifter
- $\color{bcOrange} \frac{M_j}{M_i}$ -- military capability ratio ($\gamma = 0 \implies$ no cost advantage for military superiority)

## Wars II

**Cost Distribution**

$$
\hat{c}_{ji} = \frac{c_{ji}}{V_j \left( \bm{\tau}; v_j \right)}
$$

$$
\text{Pr}\left( \frac{1}{\hat{c}_{ji}} \leq \frac{1}{\hat{c}} \right) = \hat{F}_{ji} \left( \frac{1}{\hat{c}} \right) = \exp \left( -\frac{1}{\hat{C}_j} \left( \frac{M_j}{M_i} \right)^{\gamma} ( \color{bcOrange} W_{ji} \color{black} )^{-\alpha} \hat{c}^{\eta} \right) .
$$

- $\hat{C}_j$ -- attacker-specific cost-shifter
- $\frac{M_j}{M_i}$ -- military capability ratio ($\gamma = 0 \implies$ no cost advantage for military superiority)
- $\color{bcOrange} W_{ji}$ -- geographic distance between $j$ and $i$ ($\alpha=0 \implies$ no loss of strength gradient)

. . . 

**Probability of Peace**

\begin{align*}
\hat{H}_i \left( \hat{\tilde{\bm{\tau}}}; \bm{Z}, \bm{\theta}_m \right) &= \prod_{j \neq i} \hat{F}_{ji} \left( \left( \hat{V}_j \left( \bm{1}_i; \tilde{\bm{\tau}}_{-i} \right) - \hat{V}_j \left( \hat{\tilde{\bm{\tau}}} \right) \right)^{-1} \right) \\
&= \exp \left( - \sum_{j \neq i} - \frac{1}{\hat{C}_j} \left( \frac{M_j}{M_i} \right)^{\gamma} Z_{ji}^{-\alpha} \left( \hat{V}_j \left( \bm{1}_i; \tilde{\bm{\tau}}_{-i} \right) - \hat{V}_j \left( \hat{\tilde{\bm{\tau}}} \right) \right)^{\eta} \right)
\end{align*}

. . . 

<a href="#/cost_dist">Cost Distribution Details</a>

## Optimal Policies

- Risk-return tradeoff: ideal policies balance policy optimality against threat of war
- Lower tariffs on goods from countries that pose military threats

. . .

**Best Response**

$$
\max_{\bm{\tau}_i} \quad \underbrace{\hat{H}_i(\hat{\tilde{\bm{\tau}}}; \bm{Z}, \bm{\theta}_m) \hat{V}_i(\hat{\tilde{\bm{\tau}}})}_{\text{peace}} + \underbrace{\left( 1 - \hat{H}_i(\hat{\tilde{\bm{\tau}}}; \bm{Z}, \bm{\theta}_m) \right) \hat{V}_i(\bm{1}_i; \hat{\tilde{\bm{\tau}}}_{-i})}_{\text{war}}
$$

. . .

**Equilibrium**

$$
\bm{\tau}^\star(\bm{\theta}_m, \bm{Z})
$$

. . .

- $\bm{\theta}_m = \left( \bm{v}, \gamma, \alpha, \hat{\bm{C}} \right)$ -- estimand
	+ $\bm{v}$ -- revenue thresholds (preference for protectionism)
	+ $\alpha$ -- loss of strength gradient (if $\alpha > 0$)
	+ $\gamma$ -- returns to military advantage (if $\gamma > 0$) 
	+ $\hat{\bm{C}}$ -- country-specific cost-shifters
- $\bm{Z}$ -- data

## Identification (Intuition)

**Preferences ($\bm{v}$)**

- Holding military technology fixed, $i$'s overall level of protectionism informs about $v_i$
- Governments with higher trade policies (more protectionist) have higher $v_i$

. . .

**Military Technology**

- Holding preferences fixed, heterogeneity in observed policies informs about military parameters
- $\alpha$ -- does policy favoritism covary with distance from trade partner?
- $\gamma$ -- does policy favoritism covary with military capability ratio?
- $\hat{C}_i$ -- does $i$ tend to secure favorable policies everywhere?
