## Estimation {id="estimation_main"}

**Measurement Error:** $\tau_{ij} = \tau_{ij}^\star(\bm{\theta}_m, \bm{Z}) + \epsilon_{ij}$

. . . 

**Moment Estimator**

$$
\min_{\bm{\theta}_m} \quad \sum_i \sum_j \left( \epsilon_{ij}(\bm{\theta}_m, \bm{Z}) \right)^2
$$

. . . 

**Mathematical Program with Equilibrium Constraints (MPEC) [@Su2012]**

\begin{equation*}
\begin{split}
\min_{ \bm{\theta}_m, \hat{\tilde{\bm{\tau}}}, \hat{\bm{w}}, \hat{\bm{w}}^\prime, \bm{\lambda} } & \quad \sum_i \sum_j \left( \epsilon_{ij} \right)^2 & \quad \text{} \\
\text{subject to} & \quad \nabla_{\hat{\tilde{\bm{\tau}}}_i} \mathcal{L}_i(\hat{\tilde{\bm{\tau}}}, \hat{\bm{w}}, \bm{\lambda}_i; \bm{\theta}_m) = \bm{0} \text{ for all } i & \quad \text{Policy Optimality} \\
& \quad \hat{\bm{w}} = \hat{h} \left( \hat{\tilde{\bm{\tau}}} \right) & \quad \text{GE (Proposed Policies)} \\
& \quad \hat{\bm{w}}_i^\prime = \hat{h} \left( \bm{1}_i, \hat{\tilde{\bm{\tau}}}_{-i} \right) \text{ for all } i & \quad \text{GE (Imposed Policies)}
\end{split}
\end{equation*}

<a href="#/br_mpec">Best Response MPEC</a>

. . . 

**Uncertainty:** Nonparametric bootstrap (sample policy estimates ($\tau_{ij}$) and recompute $\tilde{\bm{\theta}}_m$)

