## Model Fit {id="fit"}

```{r, echo=FALSE, warning=FALSE, message=FALSE, dpi=600, fig.align="center", fig.height=5.}

source(paste0("../", code_dir, "f_fit.R"))
fit

```

<a href="#/results_main">Back</a>

## Errors {id="errors"}

```{r, echo=FALSE, warning=FALSE, message=FALSE, dpi=600, fig.align="center", fig.height=5., dpi=1000}

# source(paste0("../", code_dir, "f_fit.R"))
fit_ddyad_small + theme(aspect.ratio=1) + theme(axis.text.y=element_text(size=4)) + scale_size(range = c(.5, .5))

```

<a href="#/results_main">Back</a>


## Non-Coercive Model {id="nce"}

```{r, echo=FALSE, warning=FALSE, message=FALSE, dpi=600, fig.align="center", fig.height=5.}

# source(paste0("../", code_dir, "f_estimates.R"))
pref_plot_mil_off

```

<a href="#/results_main">Back</a>

## Non-Coercive Model Fit {id="nce_fit"}

```{r, echo=FALSE, warning=FALSE, message=FALSE, dpi=600, fig.align="center", fig.height=5.}

# source(paste0("../", code_dir, "f_fit.R"))
fit_mo 

```

<a href="#/results_main">Back</a>

