```{r, echo=FALSE, warning=FALSE, message=FALSE, results='hide'}

use_virtualenv("python3")
c_setup <- import_from_path("c_setup", path=paste0("../", code_dir))
setup <- c_setup$setup("local", size)

```

## Parameters {id="results_main"}

```{r, echo=FALSE, warning=FALSE, message=FALSE, dpi=600, fig.align="center", fig.height=5.}

source(paste0("../", code_dir, "f_estimates.R"))

pref_plot_square <- pref_plot
mil_plot_square <- mil_plot

pref_plot_square / mil_plot_square + theme(aspect.ratio=.25)

```

<a href="#/fit">Model Fit</a>  &emsp; &emsp; <a href="#/errors">Errors</a> &emsp; &emsp; <a href="#/nce">Non-Coercive Model</a> &emsp; &emsp; <a href="#/nce_fit">Non-Coercive Model Fit</a>


## War Costs

```{r, echo=FALSE, warning=FALSE, message=FALSE, dpi=600, fig.align="center", fig.height=5.}

# source(paste0("../", code_dir, "f_estimates.R"))
costs_plot

```

## Conquest Values

```{r, echo=FALSE, warning=FALSE, message=FALSE, dpi=600, fig.align="center", fig.height=5.}

# source(paste0("../", code_dir, "f_estimates.R"))
rcv_hm

```

## War Probabilities

```{r, echo=FALSE, warning=FALSE, message=FALSE, dpi=600, fig.align="center", fig.height=5.}

# source(paste0("../", code_dir, "f_estimates.R"))
war_probs_pp

```